steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/furniture-application:$COMMIT_SHA', '-f', 'application/Dockerfile', 'application']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/furniture-application:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c' # Set the zone where the cluster is located
    - 'CLOUDSDK_CONTAINER_CLUSTER=privatecluster' # Set the name of the cluster
  args: [
    'container', 'clusters', 'get-credentials', 'privatecluster',
    '--zone', 'us-central1-c',
    '--project', '$PROJECT_ID'
  ]

- name: 'gcr.io/cloud-builders/helm'
  dir: 'helm/application/chart'
  args: [
    'upgrade', '--install', 'furniture-app-release',
    '.',
    '--set', 'image.repository=gcr.io/$PROJECT_ID/furniture-application',
    '--set', 'image.tag=$COMMIT_SHA',
    '--namespace', 'default'
  ]

- name: 'gcr.io/cloud-builders/kubectl'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=privatecluster'
  args: ['rollout', 'status', 'deployment/furniture-app-release', '--namespace', 'default']

images:
- 'gcr.io/$PROJECT_ID/furniture-application:$COMMIT_SHA'

logsBucket: 'gs://furniture_datasync'
