steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/furniture-application:$COMMIT_SHA', '-f', 'application/Dockerfile', 'application']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/furniture-application:$COMMIT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'container', 'clusters', 'get-credentials', 'privatecluster',
    '--zone', 'asia-east1-a',
    '--project', '$PROJECT_ID',
    '--internal-ip'
  ]

- name: 'gcr.io/cloud-builders/kubectl'
  env:
    - 'CLOUDSDK_CONTAINER_CLUSTER=privatecluster'
    - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
  args: ['get', 'nodes']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: [
    '-c',
    'curl -sSL https://get.helm.sh/helm-v3.16.2-linux-amd64.tar.gz | tar xz && mv linux-amd64/helm ./helm && ./helm upgrade --install furniture-app-release . --set image.repository=gcr.io/$PROJECT_ID/furniture-application --set image.tag=$COMMIT_SHA --namespace default'
  ]
  dir: 'helm/application/chart'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['rollout', 'status', 'deployment/furniture-app-release', '--namespace', 'default']

images:
- 'gcr.io/$PROJECT_ID/furniture-application:$COMMIT_SHA'

logsBucket: 'gs://application-data-sync'
